class instance:
    name = ''  # name of instance
    V_coordinates = []  # coordinates of each point
    V = []  # indices of each point
    VD = []  # indices of each depot
    VC = []  # indices of each customer
    VP = []  # indices of each parking node
    VC1 = []  # indices of each normal customer
    VC2 = []  # indices of each customer which can be serviced only by robot
    demand = []  # demand of each point
    service_time = []  # service time of each point
    K = []  # indices of vehicles
    veh_dist_matrix = []
    rob_power_matrix = []
    vehicle_cost_matrix = []  # travel cost matrix of vehicle
    robot_cost_matrix = []  # travel cost matrix of robot
    vehicle_time_matrix = []  # travel time matrix of vehicle
    robot_time_matrix = []  # travel time matrix of robot
    # --------------
    cus_with_depot = {}
    veh_with_depot = {}
    veh_depot_dict = {}  # transpose veh_with_depot
    depot_with_node = {}  # depot and all its nodes: depot + cus + parking node
    VC2_with_VP = {}
    max_travel_time = 0.0
    # fixed parameters
    cf = 50  # fixed cost of transportation
    vehicle_speed = 32
    robot_speed = 10
    vehicle_cost = 2
    robot_cost = 1
    very_big = 1e5
    veh_cap = 300
    rob_cap = 30
    veh_dist_ub = 300
    robot_ub = 3  # The battery capacity of the robot (kwh)
    robot_unit_consumption = 0.1  # Unit consumption of robot power kwh/km
    rob_weight = 30  # 好像没啥用
    operation_time = 5
    # vehicle_speed = 1
    # robot_speed = 0.2
    # vehicle_cost = 1
    # robot_cost = 0.5
    # very_big = 1e5
    # veh_cap = 200
    # rob_cap = 30
    # rob_weight = 30
    # operation_time = 5
    # veh_dist_ub = 300
    # robot_ub = 30 # The maximum battery limit of the robot
    # robot_unit_consumption = 1 # Unit consumption of robot power
